# Generated by Django 2.2 on 2021-03-26 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='creator',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='thought',
            name='liked_by',
        ),
    ]
